version: '3.9'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
      - client
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      # - /home/cert:/etc/nginx/certs
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email bhusan@ncit.edu.np -d ncit.college --agree-tos
  client:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db
    
  api:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
      # - ./public/files :/usr/app/src/files/
    depends_on:
      - mongo 
    links:
      - mongo
  
volumes:
  mongo:

