version: '3.9'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
      - client
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d
      
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  client:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db
    
  api:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - mongo 
    links:
      - mongo
  
volumes:
  mongo: